# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 455c289e464b59ddd9810baf63f94c3bf589c22c994300bb577f87da7566e8fd422fa1b0a612dcf7f57fe30ce608effb60c680d2e849a1b1e30cdcc37a806af8

test:
  secret_key_base: aa0d377260d4e3c18bd1b5de8671d0aaa347b2fe6fd07cb117180c9300cd5d327bf9bb31c67e979b51a74a6e5c2bb079887eedfbee4ed996911d335c0e4d4645

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
